name: AWS_EC2 using Terraform
on: workflow_dispatch

jobs:
  EC2_with_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Provision EC2 with Terraform
        uses: ./.github/actions/terraform-ec2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
