name: AWS_EC2 using Terraform
on: workflow_dispatch

jobs:
  EC2_with_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Provision EC2 with Terraform
        uses: ./.github/actions/terraform-ec2
        with:
          AWS_ACCESS_KEY_I: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KE: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGIO: ${{ secrets.AWS_DEFAULT_REGION }}
