name: installing java
on: workflow_dispatch
run-name: ${{ github.actor }} is installing java

jobs:
  install_java_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Java version
        run: java -version
     
      - name: Compile Java program
        run: javac HelloWorld.java  
    
    

      - name: Run Java program
        run: java -cp . HelloWorld
